unset(LBFGS_INCLUDE_DIR CACHE)
sdl_find_path(LBFGS_INCLUDE_DIR lbfgs.h ${LBFGS_ROOT}/include)
unset(LBFGS_LIB CACHE)
sdl_find_library(LBFGS_LIB NAMES lbfgs PATHS ${LBFGS_ROOT}/lib)

if (LBFGS_INCLUDE_DIR)
  SET(LBFGS_FOUND 1)
  SET(LBFGS_LIB optimized ${LBFGS_LIB} debug ${LBFGS_LIB})
  MESSAGE(STATUS "Found L-BFGS library in ${LBFGS_ROOT}")
else()
  MESSAGE(FATAL_ERROR "Could not locate L-BFGS library in ${LBFGS_ROOT}")
endif()
