#-#  Try to find the liblog4cxx libraries
# Once done this will define
#
# LOG4CXX_FOUND - system has liblog4cxx
# LOG4CXX_INCLUDE_DIR - the liblog4cxx include directory
# LOG4CXX_LIBRARIES - liblog4cxx library

MESSAGE(STATUS "log4cxx root: ${LOG4CXX_ROOT}")
unset(LOG4CXX_INCLUDE_LOG4CXX_DIR CACHE)
sdl_find_path(LOG4CXX_INCLUDE_LOG4CXX_DIR logger.h PATHS ${LOG4CXX_ROOT}/include/log4cxx)
MESSAGE(STATUS "log4cxx include: ${LOG4CXX_INCLUDE_LOG4CXX_DIR}")

unset(LOG4CXX_LIBRARY_RELEASE CACHE)
unset(LOG4CXX_LIBRARY_DEBUG CACHE)
if(APPLE)
	set(LOG4CXX_LIB_DEBUG_DIR ${LOG4CXX_LIB_DIR})	
	FIND_LIBRARY(LOG4CXX_LIBRARY_RELEASE NAMES log4cxx PATHS ${LOG4CXX_LIB_DIR} NO_DEFAULT_PATH)
	FIND_LIBRARY(LOG4CXX_LIBRARY_DEBUG NAMES log4cxx PATHS ${LOG4CXX_LIB_DEBUG_DIR} NO_DEFAULT_PATH)
ENDIF()

IF(WIN32)
	FIND_LIBRARY(LOG4CXX_LIBRARY_RELEASE NAMES log4cxx PATHS ${LOG4CXX_LIB_DIR} NO_DEFAULT_PATH)
	FIND_LIBRARY(LOG4CXX_LIBRARY_DEBUG NAMES log4cxx PATHS ${LOG4CXX_LIB_DEBUG_DIR} NO_DEFAULT_PATH)
ENDIF()

IF(UNIX AND NOT APPLE)
	FIND_LIBRARY(LOG4CXX_LIBRARY_RELEASE NAMES log4cxx PATHS ${LOG4CXX_LIB_DIR} NO_DEFAULT_PATH)
	FIND_LIBRARY(LOG4CXX_LIBRARY_DEBUG NAMES log4cxx PATHS ${LOG4CXX_LIB_DEBUG_DIR} NO_DEFAULT_PATH)
ENDIF()
MESSAGE(STATUS "log4cxx debug lib: ${LOG4CXX_LIBRARY_DEBUG}")
MESSAGE(STATUS "log4cxx release lib: ${LOG4CXX_LIBRARY_RELEASE}")


IF(LOG4CXX_INCLUDE_LOG4CXX_DIR AND (LOG4CXX_LIBRARY_RELEASE OR LOG4CXX_LIBRARY_DEBUG))
  sdl_libpath(${LOG4CXX_LIBRARY_RELEASE})
  SET(LOG4CXX_FOUND 1)
  #remove last /log4cxx string
  STRING(REGEX REPLACE "include/log4cxx" "include" LOG4CXX_INCLUDE_DIR ${LOG4CXX_INCLUDE_LOG4CXX_DIR})
  SET(LOG4CXX_LIBRARIES
     debug ${LOG4CXX_LIBRARY_DEBUG}
     optimized ${LOG4CXX_LIBRARY_RELEASE}
     )
  MESSAGE(STATUS "Found log4cxx: ${LOG4CXX_LIBRARIES}")
ELSE(LOG4CXX_INCLUDE_LOG4CXX_DIR AND (LOG4CXX_LIBRARY_RELEASE OR LOG4CXX_LIBRARY_DEBUG))
  SET(LOG4CXX_FOUND 0 CACHE BOOL "Not found log4cxx library")
  MESSAGE(FATAL_ERROR "Not found log4cxx library")
ENDIF(LOG4CXX_INCLUDE_LOG4CXX_DIR AND (LOG4CXX_LIBRARY_RELEASE OR LOG4CXX_LIBRARY_DEBUG))

MARK_AS_ADVANCED(LOG4CXX_INCLUDE_DIR LOG4CXX_LIBRARIES)
