/** \file

 .
*/

#ifndef ANNOTATIONS_JG_2015_03_27_HPP
#define ANNOTATIONS_JG_2015_03_27_HPP
#pragma once

#ifndef SDL_HYPERGRAPH_FS_ANNOTATIONS
#define SDL_HYPERGRAPH_FS_ANNOTATIONS 1
#endif
#if SDL_HYPERGRAPH_FS_ANNOTATIONS
#define IF_SDL_HYPERGRAPH_FS_ANNOTATIONS(x) x
#else
#define IF_SDL_HYPERGRAPH_FS_ANNOTATIONS(x)
#endif

#endif
